services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"

#  maildev:
#    image: maildev/maildev
#    environment:
#      - TZ=Europe/Moscow
#      - MAILDEV_WEB_PORT=1080
#      - MAILDEV_SMTP_PORT=1025
#    ports:
#      - "8080:1080"
#      - "1025:1025"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1m"
#
  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"